name: Commitlint

on:
  push:
    branches: [main, feature/*]
  pull_request:
    branches: [main, develop]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: Commitlint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Run commitlint
        run: opensource-nepal/commitlint@v1
