name: Automated Tests

on: pull_request

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pip install pytest
        pytest

    - name: Run make file
      run: |
        make test

    - name: Upload coverage to Coveralls
      run: |
        pip install coveralls
        coverage run --source=src -m pytest tests/
        coveralls

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Finish
      run: echo "All tests passed!"
